version: '3.8'
services:
  
  app:
    
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "dapp"
    image: tender-manager:v1
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/code/frontend

  
     
